/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui_kp;

import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author Lenovo
 */
public class UserInterface3_KP extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface3_KP
     */
    public UserInterface3_KP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneKesatuan = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPaneTglInput = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPanePangkat = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPaneKorps = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextPaneJenisBerkas = new javax.swing.JTextPane();
        jLabelDokumen = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextPane16 = new javax.swing.JTextPane();
        jButtonInput = new javax.swing.JButton();
        jButtonRevisi = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextPaneNama = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextPane18 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPaneNRP = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextPaneTglLahir = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane5.setToolTipText("");
        jScrollPane5.setName(""); // NOI18N

        jTextPane5.setText(" Korps     :");
        jTextPane5.setName("plain2"); // NOI18N
        jScrollPane5.setViewportView(jTextPane5);

        jTextPane11.setText("Jenis Berkas");
        jScrollPane11.setViewportView(jTextPane11);

        jScrollPane6.setToolTipText("");
        jScrollPane6.setName(""); // NOI18N

        jTextPane6.setText("Kesatuan :");
        jTextPane6.setName("plain2"); // NOI18N
        jScrollPane6.setViewportView(jTextPane6);

        jScrollPane12.setToolTipText("");
        jScrollPane12.setName(""); // NOI18N

        jTextPane12.setText("Taggal Input :");
        jTextPane12.setName("plain2"); // NOI18N
        jScrollPane12.setViewportView(jTextPane12);

        jScrollPane2.setToolTipText("");
        jScrollPane2.setName(""); // NOI18N

        jTextPane2.setText("Berkas      :");
        jTextPane2.setName("plain2"); // NOI18N
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setToolTipText("");
        jScrollPane3.setName(""); // NOI18N

        jTextPane3.setText("Tgl Lahir        :");
        jTextPane3.setName("plain2"); // NOI18N
        jScrollPane3.setViewportView(jTextPane3);

        jScrollPane4.setToolTipText("");
        jScrollPane4.setName(""); // NOI18N

        jTextPane4.setText("Pangkat  :");
        jTextPane4.setName("plain2"); // NOI18N
        jScrollPane4.setViewportView(jTextPane4);

        jScrollPane7.setToolTipText("");
        jScrollPane7.setName(""); // NOI18N

        jTextPaneKesatuan.setName("plain2"); // NOI18N
        jScrollPane7.setViewportView(jTextPaneKesatuan);

        jScrollPane13.setToolTipText("");
        jScrollPane13.setName(""); // NOI18N

        jTextPaneTglInput.setName("plain2"); // NOI18N
        jScrollPane13.setViewportView(jTextPaneTglInput);

        jScrollPane9.setToolTipText("");
        jScrollPane9.setName(""); // NOI18N

        jTextPanePangkat.setName("plain2"); // NOI18N
        jScrollPane9.setViewportView(jTextPanePangkat);

        jScrollPane10.setToolTipText("");
        jScrollPane10.setName(""); // NOI18N

        jTextPaneKorps.setName("plain2"); // NOI18N
        jScrollPane10.setViewportView(jTextPaneKorps);

        jScrollPane15.setViewportView(jTextPaneJenisBerkas);

        jLabelDokumen.setText("DOKUMEN AKAN TAMPIL DISINI");
        jLabelDokumen.setToolTipText("");

        jScrollPane16.setToolTipText("");
        jScrollPane16.setName(""); // NOI18N

        jTextPane16.setText("NRP      :");
        jTextPane16.setName("plain2"); // NOI18N
        jScrollPane16.setViewportView(jTextPane16);

        jButtonInput.setText("Input");
        jButtonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputActionPerformed(evt);
            }
        });

        jButtonRevisi.setText("Revisi");
        jButtonRevisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRevisiActionPerformed(evt);
            }
        });

        jScrollPane17.setToolTipText("");
        jScrollPane17.setName(""); // NOI18N

        jTextPaneNama.setName("plain2"); // NOI18N
        jScrollPane17.setViewportView(jTextPaneNama);

        jScrollPane18.setToolTipText("");
        jScrollPane18.setName(""); // NOI18N

        jTextPane18.setText("Nama      :");
        jTextPane18.setName("plain2"); // NOI18N
        jScrollPane18.setViewportView(jTextPane18);

        jScrollPane19.setToolTipText("");
        jScrollPane19.setName(""); // NOI18N

        jTextPaneNRP.setName("plain2"); // NOI18N
        jScrollPane19.setViewportView(jTextPaneNRP);

        jScrollPane20.setToolTipText("");
        jScrollPane20.setName(""); // NOI18N

        jTextPaneTglLahir.setName("plain2"); // NOI18N
        jScrollPane20.setViewportView(jTextPaneTglLahir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDokumen, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane12)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane16)
                            .addComponent(jScrollPane18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane10)
                            .addComponent(jScrollPane15)
                            .addComponent(jScrollPane17)
                            .addComponent(jScrollPane19)
                            .addComponent(jScrollPane20)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInput)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRevisi)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addComponent(jLabelDokumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInput)
                    .addComponent(jButtonRevisi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInputActionPerformed

    private void jButtonRevisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRevisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRevisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface3_KP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface3_KP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface3_KP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface3_KP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface3_KP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInput;
    private javax.swing.JButton jButtonRevisi;
    private javax.swing.JLabel jLabelDokumen;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane16;
    private javax.swing.JTextPane jTextPane18;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPaneJenisBerkas;
    private javax.swing.JTextPane jTextPaneKesatuan;
    private javax.swing.JTextPane jTextPaneKorps;
    private javax.swing.JTextPane jTextPaneNRP;
    private javax.swing.JTextPane jTextPaneNama;
    private javax.swing.JTextPane jTextPanePangkat;
    private javax.swing.JTextPane jTextPaneTglInput;
    private javax.swing.JTextPane jTextPaneTglLahir;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelDokumen() {
        return jLabelDokumen;
    }

    public JTextPane getjTextPaneJenisBerkas() {
        return jTextPaneJenisBerkas;
    }

    public JTextPane getjTextPaneKesatuan() {
        return jTextPaneKesatuan;
    }

    public JTextPane getjTextPaneKorps() {
        return jTextPaneKorps;
    }

    public JTextPane getjTextPaneNRP() {
        return jTextPaneNRP;
    }

    public JTextPane getjTextPaneNama() {
        return jTextPaneNama;
    }

    public JTextPane getjTextPanePangkat() {
        return jTextPanePangkat;
    }

    public JTextPane getjTextPaneTglInput() {
        return jTextPaneTglInput;
    }

    public JTextPane getjTextPaneTglLahir() {
        return jTextPaneTglLahir;
    }
}
